sudo: required
services:
  - docker
before_install:
  - docker build -t infiniteproject/torify .
script:
  - docker run -d --name torify -v /var/run/docker.sock:/tmp/docker.sock:ro infiniteproject/torify
  - docker run -d --name nginx -e TORIFY nginx
  - docker ps -a
  - docker exec torify cat /etc/tor/torrc
